### ISSUE TITLE
Crash with Minefactoryreloaded steam and tubes

### ISSUE THREAD

**Issue by tolomea** [aidancbrady/Mekanism#3329]
So this is happening, as far as I can tell the moment it started was when a minefactoryreloaded steam boiler output into a Mekanism mechanical pipe connected to a minefactoryreloaded steam turbine. I don't recall how the ends of the pipe were configured, I will go try and reproduce it in creative.
A note on codechicken, I did have nei, chicken chunks and chicken core installed, this dump is from after I removed them (as an attempt at debug) and is essentially the same as before removing them.

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/5/16 10:51 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at codechicken.lib.render.uv.IconTransformation.apply(IconTransformation.java:15)
	at codechicken.lib.render.uv.IconTransformation.apply(IconTransformation.java:6)
	at codechicken.lib.render.uv.UVTransformation.operate(UVTransformation.java:28)
	at codechicken.lib.render.CCRenderPipeline.operate(CCRenderPipeline.java:128)
	at codechicken.lib.render.CCRenderState.runPipeline(CCRenderState.java:352)
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:346)
	at codechicken.lib.render.CCModel.render(CCModel.java:430)
	at codechicken.lib.render.CCModel.render(CCModel.java:418)
	at mekanism.client.render.RenderPartTransmitter.renderTransparency(RenderPartTransmitter.java:635)
	at mekanism.client.render.RenderPartTransmitter.renderFluidInOut(RenderPartTransmitter.java:611)
	at mekanism.client.render.RenderPartTransmitter.renderContents(RenderPartTransmitter.java:361)
	at mekanism.common.multipart.PartMechanicalPipe.renderDynamic(PartMechanicalPipe.java:232)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderDynamic$1.apply(TileMultipart.scala:495)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderDynamic$1.apply(TileMultipart.scala:495)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at codechicken.multipart.TileMultipartClient$class.renderDynamic(TileMultipart.scala:495)
	at TileMultipart_cmp$$6.renderDynamic(Unknown Source)
	at codechicken.multipart.MultipartRenderer$.func_147500_a(MultipartRenderer.scala:38)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.lib.render.uv.IconTransformation.apply(IconTransformation.java:15)
	at codechicken.lib.render.uv.IconTransformation.apply(IconTransformation.java:6)
	at codechicken.lib.render.uv.UVTransformation.operate(UVTransformation.java:28)
	at codechicken.lib.render.CCRenderPipeline.operate(CCRenderPipeline.java:128)
	at codechicken.lib.render.CCRenderState.runPipeline(CCRenderState.java:352)
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:346)
	at codechicken.lib.render.CCModel.render(CCModel.java:430)
	at codechicken.lib.render.CCModel.render(CCModel.java:418)
	at mekanism.client.render.RenderPartTransmitter.renderTransparency(RenderPartTransmitter.java:635)
	at mekanism.client.render.RenderPartTransmitter.renderFluidInOut(RenderPartTransmitter.java:611)
	at mekanism.client.render.RenderPartTransmitter.renderContents(RenderPartTransmitter.java:361)
	at mekanism.common.multipart.PartMechanicalPipe.renderDynamic(PartMechanicalPipe.java:232)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderDynamic$1.apply(TileMultipart.scala:495)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderDynamic$1.apply(TileMultipart.scala:495)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at codechicken.multipart.TileMultipartClient$class.renderDynamic(TileMultipart.scala:495)
	at TileMultipart_cmp$$6.renderDynamic(Unknown Source)
	at codechicken.multipart.MultipartRenderer$.func_147500_a(MultipartRenderer.scala:38)

-- Block Entity Details --
Details:
	Name: savedMultipart // TileMultipart_cmp$$6
	Block type: ID #478 (tile.multipart // codechicken.multipart.BlockMultipart)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (919,71,1156), Chunk: (at 7,4,4 in 57,72; contains blocks 912,0,1152 to 927,255,1167), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Actual block type: ID #478 (tile.multipart // codechicken.multipart.BlockMultipart)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['tolomea'/600, l='MpServer', x=920.33, y=72.62, z=1170.79]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-280,64,-674), Chunk: (at 8,4,14 in -18,-43; contains blocks -288,0,-688 to -273,255,-673), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 2591751 game time, 3997384 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 144 total; [EntityBat['Bat'/772, l='MpServer', x=859.38, y=39.10, z=1217.50], EntityBat['Bat'/774, l='MpServer', x=859.40, y=38.71, z=1227.73], EntityPig['Pig'/778, l='MpServer', x=847.38, y=68.00, z=1172.75], EntitySlime['Slime'/781, l='MpServer', x=854.63, y=63.00, z=1122.38], EntityZombie['Zombie'/783, l='MpServer', x=856.00, y=62.00, z=1122.50], EntityCow['Cow'/787, l='MpServer', x=875.03, y=76.00, z=1106.94], EntityBat['Bat'/790, l='MpServer', x=978.90, y=39.23, z=1118.55], EntityCreeper['Creeper'/794, l='MpServer', x=980.00, y=38.00, z=1122.56], EntityBat['Bat'/796, l='MpServer', x=981.97, y=31.00, z=1146.32], EntityChicken['Chicken'/803, l='MpServer', x=998.84, y=63.37, z=1182.47], EntityBat['Bat'/807, l='MpServer', x=986.69, y=30.10, z=1230.59], EntityBat['Bat'/809, l='MpServer', x=984.34, y=29.00, z=1227.19], EntityZombie['Zombie'/810, l='MpServer', x=987.38, y=30.00, z=1224.97], EntityCow['Cow'/812, l='MpServer', x=976.09, y=74.00, z=1221.09], EntityCow['Cow'/814, l='MpServer', x=977.41, y=74.00, z=1221.09], EntityCow['Cow'/816, l='MpServer', x=980.69, y=74.00, z=1224.75], EntityCow['Cow'/818, l='MpServer', x=975.34, y=74.00, z=1225.06], EntityClientPlayerMP['tolomea'/600, l='MpServer', x=920.33, y=72.62, z=1170.79], EntityZombie['Zombie'/858, l='MpServer', x=843.50, y=36.00, z=1146.50], EntityItem['item.tile.mfr.rubberwood.sapling'/603, l='MpServer', x=896.69, y=70.13, z=1171.44], EntityPig['Pig'/859, l='MpServer', x=843.91, y=72.00, z=1148.16], EntityItem['item.tile.sapling.birch'/604, l='MpServer', x=900.00, y=74.54, z=1176.13], EntityPig['Pig'/860, l='MpServer', x=846.19, y=70.00, z=1146.72], EntityItem['item.tile.sapling.birch'/605, l='MpServer', x=898.66, y=69.13, z=1176.88], EntityPig['Pig'/861, l='MpServer', x=843.91, y=72.00, z=1150.06], EntityItem['item.tile.sapling.birch'/606, l='MpServer', x=898.63, y=69.13, z=1180.06], EntityPig['Pig'/862, l='MpServer', x=887.16, y=83.00, z=1100.03], EntityCreeper['Creeper'/607, l='MpServer', x=943.70, y=18.18, z=1176.08], EntitySlime['Slime'/863, l='MpServer', x=855.69, y=39.00, z=1234.31], EntityItem['item.item.sulphur'/608, l='MpServer', x=928.72, y=40.13, z=1169.47], EntityZombie['Zombie'/864, l='MpServer', x=856.72, y=37.00, z=1238.22], EntityZombie['Zombie'/609, l='MpServer', x=939.03, y=38.00, z=1171.53], EntityCreeper['Creeper'/865, l='MpServer', x=849.25, y=39.00, z=1232.75], EntityChicken['Chicken'/610, l='MpServer', x=936.15, y=70.56, z=1179.85], EntityZombie['Zombie'/866, l='MpServer', x=861.50, y=38.00, z=1240.50], EntityChicken['Chicken'/611, l='MpServer', x=936.15, y=70.62, z=1178.70], EntityCreeper['Creeper'/867, l='MpServer', x=848.31, y=39.00, z=1232.31], EntityChicken['Chicken'/612, l='MpServer', x=936.16, y=71.48, z=1176.85], EntityPig['Pig'/868, l='MpServer', x=856.28, y=63.00, z=1236.78], EntityChicken['Chicken'/613, l='MpServer', x=936.16, y=71.45, z=1175.39], EntityChicken['Chicken'/614, l='MpServer', x=936.50, y=70.54, z=1177.19], EntityBat['Bat'/870, l='MpServer', x=856.38, y=61.92, z=1117.00], EntityChicken['Chicken'/615, l='MpServer', x=936.15, y=71.23, z=1177.59], EntitySlime['Slime'/871, l='MpServer', x=858.53, y=64.00, z=1107.31], EntityChicken['Chicken'/616, l='MpServer', x=936.16, y=70.59, z=1176.28], EntityChicken['Chicken'/872, l='MpServer', x=979.53, y=64.00, z=1113.72], EntityItem['item.tile.mfr.rubberwood.sapling'/617, l='MpServer', x=901.13, y=70.13, z=1167.88], EntityZombie['Zombie'/873, l='MpServer', x=989.54, y=42.96, z=1246.50], EntityItem['item.tile.mfr.rubberwood.sapling'/618, l='MpServer', x=902.81, y=71.13, z=1160.19], EntityCreeper['Creeper'/619, l='MpServer', x=938.31, y=19.98, z=1167.69], EntityCreeper['Creeper'/620, l='MpServer', x=940.50, y=37.00, z=1165.50], EntityCreeper['Creeper'/621, l='MpServer', x=940.00, y=32.00, z=1195.50], EntitySheep['Sheep'/877, l='MpServer', x=956.06, y=71.00, z=1102.97], EntityItem['item.tile.mfr.rubberwood.sapling'/622, l='MpServer', x=894.81, y=70.13, z=1168.88], EntityItem['item.tile.mfr.rubberwood.sapling'/623, l='MpServer', x=895.81, y=70.13, z=1171.00], EntitySkeleton['Skeleton'/624, l='MpServer', x=925.50, y=21.00, z=1139.50], EntityCow['Cow'/625, l='MpServer', x=885.76, y=68.00, z=1163.53], EntityCow['Cow'/626, l='MpServer', x=882.07, y=68.00, z=1165.93], EntityCow['Cow'/627, l='MpServer', x=885.73, y=68.00, z=1162.31], EntityCow['Cow'/628, l='MpServer', x=884.56, y=68.00, z=1161.07], EntityCow['Cow'/629, l='MpServer', x=883.54, y=68.00, z=1165.93], EntityCow['Cow'/630, l='MpServer', x=882.09, y=68.00, z=1162.31], EntityCow['Cow'/631, l='MpServer', x=886.91, y=68.00, z=1164.69], EntityCow['Cow'/632, l='MpServer', x=883.29, y=68.00, z=1163.50], EntityCow['Cow'/633, l='MpServer', x=886.93, y=68.00, z=1164.52], EntityCow['Cow'/634, l='MpServer', x=882.07, y=68.00, z=1164.71], EntityCow['Cow'/635, l='MpServer', x=885.71, y=68.00, z=1165.93], EntityCow['Cow'/636, l='MpServer', x=882.07, y=68.00, z=1163.43], EntityCow['Cow'/637, l='MpServer', x=886.93, y=68.00, z=1165.91], EntityCow['Cow'/638, l='MpServer', x=884.57, y=68.00, z=1163.46], EntityCow['Cow'/639, l='MpServer', x=883.37, y=68.00, z=1162.54], EntityCow['Cow'/640, l='MpServer', x=884.56, y=68.00, z=1162.29], EntityCow['Cow'/641, l='MpServer', x=884.61, y=68.00, z=1164.54], EntityCow['Cow'/642, l='MpServer', x=883.32, y=68.00, z=1161.07], EntityCow['Cow'/643, l='MpServer', x=883.26, y=68.00, z=1164.69], EntityCreeper['Creeper'/899, l='MpServer', x=845.63, y=36.00, z=1238.03], EntityCow['Cow'/644, l='MpServer', x=886.91, y=68.00, z=1163.35], EntitySpider['Spider'/900, l='MpServer', x=851.94, y=43.06, z=1093.81], EntityCow['Cow'/645, l='MpServer', x=885.75, y=68.00, z=1161.09], EntityCow['Cow'/646, l='MpServer', x=882.09, y=68.00, z=1161.07], EntityMinecartChest['entity.MinecartChest.name'/902, l='MpServer', x=983.50, y=31.50, z=1091.50], EntitySlime['Slime'/647, l='MpServer', x=887.06, y=68.00, z=1161.45], EntityItem['item.item.mfr.rubber.raw'/648, l='MpServer', x=891.94, y=69.13, z=1164.88], EntityItem['item.tile.mfr.rubberwood.sapling'/649, l='MpServer', x=894.12, y=70.13, z=1159.06], EntityItem['item.tile.mfr.rubberwood.sapling'/650, l='MpServer', x=891.06, y=69.13, z=1166.44], EntityItem['item.tile.mfr.rubberwood.sapling'/651, l='MpServer', x=894.22, y=75.13, z=1160.44], EntityZombie['Zombie'/652, l='MpServer', x=900.53, y=57.23, z=1147.56], EntityBat['Bat'/653, l='MpServer', x=899.31, y=59.10, z=1144.41], EntityCow['Cow'/654, l='MpServer', x=935.53, y=73.00, z=1205.53], EntitySkeleton['Skeleton'/655, l='MpServer', x=891.06, y=17.00, z=1141.44], EntitySkeleton['Skeleton'/656, l='MpServer', x=956.74, y=31.04, z=1138.01], EntitySpider['Spider'/657, l='MpServer', x=925.84, y=28.00, z=1132.47], EntitySkeleton['Skeleton'/658, l='MpServer', x=927.97, y=28.00, z=1127.03], EntitySkeleton['Skeleton'/659, l='MpServer', x=925.84, y=27.00, z=1134.72], EntitySkeleton['Skeleton'/660, l='MpServer', x=925.47, y=28.00, z=1128.00], EntitySkeleton['Skeleton'/661, l='MpServer', x=931.60, y=28.78, z=1126.50], EntitySpider['Spider'/662, l='MpServer', x=927.09, y=28.00, z=1130.91], EntitySpider['Spider'/663, l='MpServer', x=923.00, y=30.00, z=1133.25], EntitySkeleton['Skeleton'/664, l='MpServer', x=926.59, y=18.00, z=1134.69], EntityPig['Pig'/665, l='MpServer', x=875.97, y=68.00, z=1206.16], EntitySkeleton['Skeleton'/666, l='MpServer', x=900.13, y=19.00, z=1132.50], EntityPig['Pig'/667, l='MpServer', x=888.53, y=66.43, z=1219.59], EntitySlime['Slime'/668, l='MpServer', x=893.69, y=64.00, z=1231.69], EntityPig['Pig'/669, l='MpServer', x=878.50, y=67.00, z=1215.75], EntitySkeleton['Skeleton'/670, l='MpServer', x=949.50, y=37.00, z=1128.96], EntitySkeleton['Skeleton'/671, l='MpServer', x=959.50, y=41.00, z=1123.50], EntityPig['Pig'/672, l='MpServer', x=965.97, y=66.00, z=1144.16], EntityBat['Bat'/673, l='MpServer', x=968.94, y=26.10, z=1204.88], EntityZombie['Zombie'/674, l='MpServer', x=952.50, y=34.00, z=1221.50], EntityWitch['Witch'/675, l='MpServer', x=860.06, y=31.00, z=1182.47], EntityZombie['Zombie'/676, l='MpServer', x=859.48, y=22.03, z=1184.50], EntityPig['Pig'/677, l='MpServer', x=919.53, y=69.00, z=1112.31], EntitySlime['Slime'/678, l='MpServer', x=986.69, y=31.00, z=1173.37], EntityZombie['Zombie'/679, l='MpServer', x=855.95, y=31.00, z=1186.66], EntityCreeper['Creeper'/680, l='MpServer', x=857.41, y=21.00, z=1187.00], EntityPig['Pig'/681, l='MpServer', x=850.94, y=67.00, z=1187.75], EntityPig['Pig'/682, l='MpServer', x=843.06, y=66.00, z=1193.06], EntityPig['Pig'/683, l='MpServer', x=857.94, y=69.00, z=1165.06], EntityCow['Cow'/684, l='MpServer', x=904.75, y=79.00, z=1119.31], EntityPig['Pig'/685, l='MpServer', x=931.50, y=69.00, z=1112.31], EntityCow['Cow'/686, l='MpServer', x=930.06, y=69.00, z=1109.91], EntityZombie['Zombie'/687, l='MpServer', x=983.50, y=45.00, z=1164.50], EntityCow['Cow'/688, l='MpServer', x=977.75, y=68.00, z=1188.25], EntitySlime['Slime'/689, l='MpServer', x=934.68, y=57.29, z=1247.31], EntityPig['Pig'/690, l='MpServer', x=864.78, y=63.00, z=1230.38], EntityPig['Pig'/691, l='MpServer', x=865.31, y=61.00, z=1127.47], EntityCow['Cow'/693, l='MpServer', x=974.09, y=74.00, z=1223.09], EntityCow['Cow'/694, l='MpServer', x=976.44, y=74.00, z=1225.91], EntityCow['Cow'/695, l='MpServer', x=974.09, y=74.00, z=1224.41], EntitySkeleton['Skeleton'/696, l='MpServer', x=887.50, y=34.00, z=1237.50], EntityZombie['Zombie'/700, l='MpServer', x=848.58, y=39.57, z=1214.50], EntityCow['Cow'/702, l='MpServer', x=861.69, y=65.00, z=1206.47], EntityEnderman['Enderman'/729, l='MpServer', x=863.75, y=15.00, z=1138.50], EntityChicken['Chicken'/474, l='MpServer', x=992.53, y=64.00, z=1126.53], EntityItemFrame['entity.ItemFrame.name'/480, l='MpServer', x=1053.50, y=66.50, z=1109.94], EntityItemFrame['entity.ItemFrame.name'/481, l='MpServer', x=1043.06, y=66.50, z=1117.50], EntityItemFrame['entity.ItemFrame.name'/486, l='MpServer', x=1043.06, y=66.50, z=1123.50], EntitySlime['Slime'/746, l='MpServer', x=849.78, y=69.67, z=1138.22], EntitySkeleton['Skeleton'/750, l='MpServer', x=951.03, y=37.00, z=1106.47], EntityZombie['Zombie'/754, l='MpServer', x=984.50, y=27.00, z=1141.50], EntityZombie['Zombie'/755, l='MpServer', x=985.50, y=27.00, z=1138.50], EntityZombie['Zombie'/756, l='MpServer', x=985.50, y=27.00, z=1139.50], EntityBat['Bat'/757, l='MpServer', x=980.28, y=34.00, z=1138.78], EntityBat['Bat'/767, l='MpServer', x=873.44, y=40.10, z=1242.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 267724824 bytes (255 MB) / 746688512 bytes (712 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 45 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	AppleCore{1.3.1} [AppleCore] (AppleCore-mc1.7.10-1.3.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V13b.jar) 
	UCHIJAAAA	GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V13a.jar) 
	UCHIJAAAA	helpfulvillagers{1.3.1} [Helpful Villagers] (helpfulvillagers-1.7.10-1.3.1.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	Mekanism{9.0.2} [Mekanism] (Mekanism-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	MekanismTools{9.0.2} [MekanismTools] (MekanismTools-1.7.10-9.0.2.271.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.1} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.1.jar) 
	UCHIJAAAA	TextureGeneratorLib{0.2} [TextureGeneratorLib] (TextureGeneratorLib-1.7.10_vBeta2.jar) 
	UCHIJAAAA	WTFCore{1.7} [WhiskyTangoFox's Core] (WTFCore-1.7.10_v1.7.jar) 
	UCHIJAAAA	CaveBiomes{1.6} [WhiskyTangoFox's CaveBiomes] (WTFCaveBiomes-1.7.10_v1.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce GTX 670/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.2-325
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by aidancbrady** [comment]
This has been reported in the past- I'll talk a look at it again when I get home, but from what I remember this is on CCLib's end.

**Comment by tolomea** [comment]
Do you know any work arounds?
And do you know if going in with an editor and deleting the pipe's recover the world?

**Comment by tolomea** [comment]
And thanks for the prompt reply btw.
I can reproduce this in creative, it's definitely as described, I'm just trying to minimise the reproduction at the moment.

**Comment by aidancbrady** [comment]
Yeah, that should fix it. I don't know of any workarounds right now :/

**Comment by tolomea** [comment]
Is the tl;dnr that minefactoryreload steam is not currently compatible with Mekanism pipes?

**Comment by tolomea** [comment]
Minimum reproduction is a minefactoryreloaded steam boiler connected to a single Mekanism pipe in pull mode as soon as the boiler hits 100 it outputs steam and the game crashes

**Comment by aidancbrady** [comment]
Huh. There's a chance it may be returning a null icon. I'll reopen to remind myself to look.

**Comment by HadesDurin** [comment]
is the issue still there with latest mekanism build 9.0.2.273?

**Comment by tolomea** [comment]
ok, sorry about the slow reply, I am now unable to reproduce this the couple of worlds I did reproduce it in yesterday are still broken, I haven't tried recovering them yet, as for today I haven't managed to make it happen again

**Comment by tolomea** [comment]
deleting the offending pipe in mcedit recovered the world, if I go back in and place it again it crashes as soon as I change the mode on the pipe from normal to push (trying to get to pull of course)

**Comment by aidancbrady** [comment]
Fixed!

**Comment by tolomea** [comment]
Thanks
