### ISSUE TITLE
Mekanism Util 1.11.2 Array Crash

### ISSUE THREAD

**Issue by Kashdeya** [aidancbrady/Mekanism#4497]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
You are using a ArrayList in your code that needs to be changed to the something like below

`List<IRecipe> recipes = (List) CraftingManager.getInstance().getRecipeList();`

instead of using ArrayList

#### Steps to reproduce:
1.install Mekanism along side Bookshlft by Darkhax
2.start pack
3.crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.0.2366
**Mekanism:** 9.3.2.307
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/ur1XxzeK

**Comment by thommy101** [comment]
@aidancbrady Please release a new version.. This must be the tenth report of this... 

@Kashdeya this has been fixed and will be in the next release ;)

**Comment by NicosaurusRex99** [comment]
Me 2 https://pastebin.com/SBK5r7rw

**Comment by IncognitoJam** [comment]
I have also encountered this issue as well. It requires an urgent update release. https://pastebin.com/mpm5wF3Q

**Comment by dmodoomsirius** [comment]
@thommy101 I have the same crash latest of mekanism, 

https://gist.github.com/dmodoomsirius/68d5c16a69b417bb53131ee77dc55a77 here is my crash report.

**Comment by wMaestro** [comment]
Just going to add my voice to the masses, in case the release I got off Aidan's site was the one that was supposed to fix this. I can't see when it was released, but either way, the bug is still present in **Mekanism .309** for MC 1.11.2 with **Forge .2386** (and a ton of other mods, including the offending Bookshelf "coremod" mentioned above).

https://pastebin.com/raw/62j29bnm

**Comment by thiakil** [comment]
No, for reference you can check @ http://aidancbrady.com/mekanism/download/legacy/ which lists the changes that made it into that release.

You could probably match the dates on curseforge too.

**Comment by ceiphas** [comment]
Still waiting, Server stays down, Players are Sad :-(((

**Comment by thommy101** [comment]
@ceiphas I can build an up to date version for you. It's not an official version but should contain a fix for this. Should be installed on cliënt and server as it has some extra features.

**Comment by thommy101** [comment]
I've added a build of the current 1.11 branch as zip to the original issue #4414.

**Comment by ceiphas** [comment]
yaaay, my server is up and running

**Comment by Kashdeya** [comment]
I see that you have released a 1.10.2 update. Will you be releasing the 1.11.2 update to fix the ARRAY crash?
