### ISSUE TITLE
2 suggestions + 1 bug.

### ISSUE THREAD

**Issue by Moobien** [aidancbrady/Mekanism#4613]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Hey I am not sure if this has been raised to your attention or not but i am having an issue with the latest version for 1.11.2 where once i leave an area and return my pipes seem to disconnect. I end up with reactors (extreme reactors) almost going critical because the steam pipes disconnect and also end up with items that have 'fallen' out of the pipes.

Suggestion 1: a chunk loading machine would be very useful, currently the only chunk loading in mek is the addon for the digital miner.

Suggestion 2: make the bins lockable. Meaning that you can lock it to a specific item so that nothing else will go into it other than that item once it has been emptied. (Like you can with jabba and yabba)

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Moobien** [comment]
Currently am using a yabba barrel sitting on a bin to lock the bins input.

**Comment by thiakil** [comment]
Please post your exact versions, as this should have been fixed just recently.

> currently the only chunk loading in mek is the addon for the digital miner.

Actually the Anchor upgrade also goes in the Teleporter, and recently the Entangleporter

Your second suggestion has already been requested as part of #3735

**Comment by Moobien** [comment]
9.3.3.312 is the version i am using

**Comment by thiakil** [comment]
you are two versions behind, going by the curseforge page.

>Version (make sure you are on the latest version before reporting)

**Comment by Moobien** [comment]
Updated to latest version.  (9.3.4-fix) Logged in and out of the game several times and I am still having the mechanical pipe disconnection issue. It seems though that they only disconnect from the Extreme Reactors multiblock structures (reactors and turbines)
